### PR TITLE
feat/update-banner-design

### PR DESCRIPTION
**Pull request by lauridskern**
This PR adds the new banner design matching the docs

image

### CODE REVIEW

**Comment by hannojg** [comment]
bro, unnormal fresh

**Comment by mrousavy** [comment]
bro damn

**Comment by mrousavy** [comment]
who let him cook

**Comment by mrousavy** [comment]
image

**Comment by mrousavy** [comment]
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>

<tr>
<td width="50%">

</td>
<td width="50%">

</td>
</tr>

<tr>
<td width="50%">

</td>
<td width="50%">

</td>
</tr>

</table>

**Comment by mrousavy** [comment]
The banners you have removed are used on https://github.com/mrousavy/nitro/tree/main/packages/react-native-nitro-modules. Can you re-add them?

**Comment by lauridskern** [comment]
> The banners you have removed are used on https://github.com/mrousavy/nitro/tree/main/packages/react-native-nitro-modules. Can you re-add them?

Ops, will add them back

**Comment by mrousavy** [comment]
ty boo

**Pull request merged**
