### PR TITLE
Add swiftBridgeAdditionalHeader

### PR DESCRIPTION
**Pull request by fbeccaceci**
I added a field in nitro config to add an import for an header file in the nitrogen generated autolinking file, i needed this because trying to use nitromodules together with Fabric i needed to expose swift classes to Objective-C++, and when those swift classes extend some protocol imported from a framework, eg. CLLocationManagerDelegate, the xcode generated ProjectName-Swift.h file includes that protocol but imports the library with @import sintax which is not supported by default in c++ and enabling c++ modules broke other stuff in react-native compilation, so my solution for my project files was to import manually corelocation before importing the Project-Swift.h file, but i cannot do that in nitrogen generated files.

### CODE REVIEW

**Comment by mrousavy** [comment]
Sorry but I dont get this. Why not just create a `.mm` file yourself and add the include there?

**Comment by mrousavy** [comment]
I dont think this should be Nitro's/Nitrogen's duty.

**Comment by fbeccaceci** [comment]
> Sorry but I dont get this. Why not just create a `.mm` file yourself and add the include there?

I'm already doing this for the files i manage myself, but i the build fails because of the import in the Autolinking file generated by nitrogen.

**Comment by mrousavy** [comment]
Please share error logs.

**Comment by fbeccaceci** [comment]
```
CompileC /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/MapboxNavigationAutolinking-562159c93c3968b57f956d3945a6ed66.o /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigationAutolinking.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'MapboxNavigation' from project 'Pods')
    cd /Users/ipla/Dev/MapboxNavigation/example/ios/Pods
    
    Using response file: /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp
    
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/ipla/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.0-22A3362-db63dc9361471f152f572502bdbfe70a.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/ipla/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Index.noindex/DataStore -Wno-comma -Wno-shorten-64-to-32 @/Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -DRCT_NEW_ARCH_ENABLED\=1 -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -DFOLLY_CFG_NO_COROUTINES\=1 -DFOLLY_HAVE_CLOCK_GETTIME\=1 -Wno-comma -Wno-shorten-64-to-32 -include /Users/ipla/Dev/MapboxNavigation/example/ios/Pods/Target\ Support\ Files/MapboxNavigation/MapboxNavigation-prefix.pch -MMD -MT dependencies -MF /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/MapboxNavigationAutolinking-562159c93c3968b57f956d3945a6ed66.d --serialize-diagnostics /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/MapboxNavigationAutolinking-562159c93c3968b57f956d3945a6ed66.dia -c /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigationAutolinking.mm -o /Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/MapboxNavigationAutolinking-562159c93c3968b57f956d3945a6ed66.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/MapboxNavigation.build/Objects-normal/arm64/MapboxNavigationAutolinking-562159c93c3968b57f956d3945a6ed66.o

In file included from /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigationAutolinking.mm:10:
In file included from /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigation-Swift-Cxx-Umbrella.hpp:26:
/Users/ipla/Dev/MapboxNavigation/example/ios/Pods/Headers/Private/NitroModules/ArrayBufferHolder.hpp:38:46: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
   38 |   static ArrayBufferHolder makeBuffer(uint8_t* data, size_t size, SwiftClosure destroy) {
      |                                              ^
/Users/ipla/Dev/MapboxNavigation/example/ios/Pods/Headers/Private/NitroModules/ArrayBufferHolder.hpp:38:46: note: insert '_Nullable' if the pointer may be null
   38 |   static ArrayBufferHolder makeBuffer(uint8_t* data, size_t size, SwiftClosure destroy) {
      |                                              ^
      |                                                _Nullable
/Users/ipla/Dev/MapboxNavigation/example/ios/Pods/Headers/Private/NitroModules/ArrayBufferHolder.hpp:38:46: note: insert '_Nonnull' if the pointer should never be null
   38 |   static ArrayBufferHolder makeBuffer(uint8_t* data, size_t size, SwiftClosure destroy) {
      |                                              ^
      |                                                _Nonnull
In file included from /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigationAutolinking.mm:10:
In file included from /Users/ipla/Dev/MapboxNavigation/nitrogen/generated/ios/MapboxNavigation-Swift-Cxx-Umbrella.hpp:41:
/Users/ipla/Library/Developer/Xcode/DerivedData/MapboxNavigationExample-esrdfiejjzuzupdovukuudgsixhm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxNavigation.build/DerivedSources/MapboxNavigation-Swift.h:321:84: error: cannot find protocol declaration for 'CLLocationManagerDelegate'; did you mean 'NSLayoutManagerDelegate'?
  321 | @interface MapboxNavigationViewContentWrapper (SWIFT_EXTENSION(MapboxNavigation)) <CLLocationManagerDelegate>
      |                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                    NSLayoutManagerDelegate
In file included from <built-in>:1:
In file included from /Users/ipla/Dev/MapboxNavigation/example/ios/Pods/Target Support Files/MapboxNavigation/MapboxNavigation-prefix.pch:2:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitCore.h:235:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSLayoutManager.h:307:36: note: 'NSLayoutManagerDelegate' declared here
  307 | API_UNAVAILABLE(watchos) @protocol NSLayoutManagerDelegate <NSObject>
      |                                    ^
1 warning and 1 error generated.
```

Here is the error, as you can see the problem is that MapboxNavigation-Swift.h includes a reference to the CLLocationManagerDelegate implemented by a Swift class exposed to objective-c (because i use it in the fabric component). 
MapboxNavigationAutolinking.mm imports
```
#import "MapboxNavigation-Swift-Cxx-Umbrella.hpp"
```
Which imports MapboxNavigation-Swift.h

Inside of MapboxNavigation-Swift.h i can see the CoreLocation import
```
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import CoreLocation;
@import UIKit;
#endif
```

but in .mm files it does not work because c++ modules are disabled by default and enabling them breaks other stuff in react-native compilation, so the 2 workarounds i found are manually importing CoreLocation like this
```
#import <CoreLocation/CoreLocation.h>
```
Before importing MapboxNavigation-Swift-Cxx-Umbrella.hpp

or wrapping the class i expose to objective-c with another class that does not include reference to CLLocationManagerDelegate which is cumbersome and not applicable in every case.

**Comment by mrousavy** [comment]
tbh I dont think adding imports to the nitrogenerated header is a solution.

This should be possible somehow differently. Can you change the bridging header in your pod to your own header?

**Comment by fbeccaceci** [comment]
The Swift -> Objective-c header is autogenerated by xcode and i cannot change it, adding a Objective-c -> Swift bridging header is not possibile cause i'm in a pod ad xcode complains that it can be done only in applications. I haven't found any other way to fix this other than adding the required imports manually before the MapboxNavigation-Swift.h import

**Comment by mrousavy** [comment]
This is where you can set a custom bridging header.

Screenshot 2024-10-22 at 12 29 45

**Comment by mrousavy** [comment]
Or via `podspec`:

```rb
s.pod_target_xcconfig = {
  # ...
  "SWIFT_OBJC_BRIDGING_HEADER" => "YourCustomBridgingHeader.h"
}
```

**Comment by fbeccaceci** [comment]
I already tried that but i got this error

```
error: Using bridging headers with framework targets is unsupported (in target 'MapboxNavigation' from project 'Pods')
```

**Comment by fbeccaceci** [comment]
Also SWIFT_OBJC_INTERFACE_HEADER_NAME allows to change the name of the generated header file, this pr would allow nitrogen to support that as well, i would change the name of the field i added in this case

**Comment by fbeccaceci** [comment]
I found another solution which i find it to be the better of the 3 for now, i changed the xcode generated header name from the podspec like this

```
s.pod_target_xcconfig    = {
    "SWIFT_OBJC_INTERFACE_HEADER_NAME" => "AnotherHeader.h"
  }
```

Then i manually created a MapboxNavigation-Swift.h file that includes the necessary imports.

This PR is probably no longer necessary.

**Comment by mrousavy** [comment]
That's what I said above tho, no?

But glad you got it working 🙏

**Comment by fbeccaceci** [comment]
Not exactly, i had to change the name of the header file xcode generates for Swift -> Objective-C communication, you where suggesting to add the bridging header for Objective-C -> Swift that i cannot add being in a pod, as far as i understand the Objective-C -> Swift side is handled by cocoapods through the umbrella header it generates.

Anyway i managed to get it working.

**Pull request closed without merging**
